### ISSUE TITLE
Derive shared secret sometimes returns smaller key

### ISSUE THREAD

**Issue by waj** [mwmiller/curve25519_ex#1]
I think the result is missing a zero padding, but you might know better 😉 
Here's an example:

```elixir
our_private = <<215, 135, 186, 216, 126, 15, 83, 142, 53, 51, 5, 2, 73, 3, 193, 227, 101, 63, 248, 167, 248, 48, 88, 13, 83, 203, 109, 125, 110, 205, 123, 168>>
their_public = <<125, 22, 163, 193, 177, 127, 54, 22, 143, 210, 183, 47, 102, 74, 91, 146, 79, 78, 82, 122, 87, 164, 7, 130, 186, 236, 171, 207, 170, 4, 166, 9>>

secret = Curve25519.derive_shared_secret(our_private, their_public)
:erlang.size(secret) # => 31
```

BTW, this causes `Kcl` to crash with such keys.

**Comment by waj** [comment]
I compared the computed key with the values generated by other libraries and effectively the conversion from integer to binary is missing the padding.

I just sent a PR with the fix. I hope you like it!

**Comment by mwmiller** [comment]
New versions of the affected libraries have been released to hex.

Thank you once more for the excellent contribution.
